### ISSUE TITLE
Amazon vms Docker Swarm issue - Services  deployed in worker nodes were not accessible from master

### ISSUE THREAD

**Issue by anandhakumarpalanisamy** [bityoga/fabric_as_code#23]
**Amazon vms Docker Swarm issue - Services  deployed in worker nodes were not accessible from master**

Containers not reachable from one host to another. 

**Findings** : This issue is caused by the public, private ip system in amazon vms . 

![Screenshot from 2020-07-23 23-02-08](https://user-images.githubusercontent.com/30879156/88338435-a1860900-cd38-11ea-9335-3a727eba6174.png)

Reference : https://github.com/docker/classicswarm/issues/2687#issuecomment-324610015

**Comment by Yamakasi** [comment]
I have this issue with Hetzner at the moment and I wonder if you can tell me more about the internal network which should be usable for node management. 

Could there be an ingress vxlan 4096 issue there maybe ?

I would assume that container traffic should be possible to put over LAN instead of WAN or do you get routing issues then because it doesn't know how to go outside again ?

I hope you still respond on this closed ticket.

**Comment by anandhakumarpalanisamy** [comment]
> I have this issue with Hetzner at the moment and I wonder if you can tell me more about the internal network which should be usable for node management.
> 
> Could there be an ingress vxlan 4096 issue there maybe ?
> 
> I would assume that container traffic should be possible to put over LAN instead of WAN or do you get routing issues then because it doesn't know how to go outside again ?
> 
> I hope you still respond on this closed ticket.

Hi @Yamakasi,  

I checked your mentioned issue . 
I saw  your comment  that you have resolved your issue . you had mentioned that the issue was due to some MTU problems. 
I hope that you have already resolved your issue.
